- hosts: all
  roles:
    - role: common
    - role: souenzzo.pathogit
      pathogen_plugins:
      - repo: "https://tpope.io/vim/speeddating.git"
      - repo: "https://github.com/jceb/vim-orgmode"
      - repo: "https://github.com/editorconfig/editorconfig-vim"
      - repo: "https://github.com/plasticboy/vim-markdown.git"
    - role: geerlingguy.git
      become: true
    - role: geerlingguy.php
      become: true
    - role: geerlingguy.composer
      become: true
    - role: andrewrothstein.node
      become: true
    - role: geerlingguy.docker
      become: true
      docker_users:
        - "{{ user }}"
    - role: andrewrothstein.kubectl
      become: true
    - role: gantsign.atom
      become: true
      users:
        - username: "{{ user }}"
          atom_packages:
            - atom-beautify
            - atom-debug-ui
            - atom-ide-ui
            - busy-signal
            - editorconfig
            - file-icons
            - ide-php
            - intentions
            - language-ansible
            - language-docker
            - language-gherkin
            - language-pug
            - language-terraform
            - language-vue
            - linter-ansible-linting
            - linter-ansible-syntax
            - linter-coffeelint
            - linter-docker
            - linter-eslint
            - linter-htmlhint
            - linter-phpcs
            - linter-phpmd
            - linter-proselint
            - linter-pug
            - linter-pylint
            - linter-rubocop
            - linter-sass-lint
            - linter-spell
            - linter-spell-latex
            - linter-stylelint
            - linter-ui-default
            - linter-textlint
            - php-debug
            - prettier-atom
            - sort-lines
            - todo-show
    - role: gantsign.antigen
      become: true
      users:
        - username: "{{ user }}"
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: spaceship
            url: https://github.com/denysdovhan/spaceship-zsh-theme
          antigen_bundles:
            - name: docker-compose
            - name: git
            - name: npm
            - name: pip

